name: Deploy to GitHub Pages

on:
  push:
    branches: [v4]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npx update-browserslist-db@latest

      - name: Build
        run: npm run build

      - name: Add custom domain and nojekyll
        run: |
          touch out/.nojekyll
          echo "hiversoft.com" > out/CNAME

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: out
          clean: true
          clean-exclude: |
            .nojekyll
            CNAME